
# This include the common make file
-include ../common/Makefile-common

BUILD_DIR = ../../build

$(BUILD_DIR)/test-util.o: ./test-util.cpp ./test-util.h
	$(CXX) -c ./test-util.cpp -o $(BUILD_DIR)/test-util.o $(CXXFLAGS) $(LDFLAGS)