
#
# This makefile compiles test utility
#

SRC_DIR = ../
BUILD_DIR = ../../build

# This include the common make file
-include ../common/Makefile-common

$(info = Compiling testing utility...)

-include ../common/Makefile-compile-cpp