
#
# This makefile compiles test utility
#

# This include the common make file
-include ../common/Makefile-common

BUILD_DIR = ../../build

$(info = Compiling testing utility...)

-include ../common/Makefile-compile-cpp