
#
# This file compiles common utility files
#

# This include the common make file
-include ../common/Makefile-common

BUILD_DIR = ../../build

$(info = Compiling common utility...)

-include ../common/Makefile-compile-cpp